import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navabar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Cogniprompt',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='light'>
      <body>
      <Navbar />
      {children}
      
      </body>
    </html>
  )
}
